### ISSUE TITLE
Using node "retrieve forecast" does not work anymore - deprecated message

### ISSUE THREAD

**Issue by slaudel** [energychain/node-red-gsi#7]
Using the node "retrieve forecast" results in the following error message:

_DEPRECATION Warning: Getting GrünstromIndex without a key or account parameter will not be possible after March 1st 2021. Checkout API Docs at https://corrently.io/ for further info and to get a free key._

There should be a config option to define an api key and this api key should be sent with the api request.

**Comment by zoernert** [comment]
As of v1.5 of the module all new API endpoints are used. Please update to latest.
